import { ChainId } from '@/types/shared'
import { DepositDestination } from './types'

export { fetchDepositDestinations } from '@/lib/data/destinationsFetcher'

export const DEPOSIT_DESTINATIONS: DepositDestination[] = [
  // Ethereum
  {
    id: 'aave-usdc-eth',
    protocol: 'aave',
    chain: 'ethereum',
    token: 'USDC',
    apy: 0.042,
    apyMean30d: 0.041,
    apyBase: 0.042,
    apyReward: null,
    displayName: 'Aave V3 — USDC',
    outputTokenSymbol: 'aUSDC',
    apyType: 'variable',
    tvlUsd: 150_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'aave-weth-eth',
    protocol: 'aave',
    chain: 'ethereum',
    token: 'WETH',
    apy: 0.018,
    apyMean30d: 0.017,
    apyBase: 0.018,
    apyReward: null,
    displayName: 'Aave V3 — WETH',
    outputTokenSymbol: 'aWETH',
    apyType: 'variable',
    tvlUsd: 500_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'aave-wbtc-eth',
    protocol: 'aave',
    chain: 'ethereum',
    token: 'WBTC',
    apy: 0.011,
    apyMean30d: 0.010,
    apyBase: 0.011,
    apyReward: null,
    displayName: 'Aave V3 — WBTC',
    outputTokenSymbol: 'aWBTC',
    apyType: 'variable',
    tvlUsd: 200_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'morpho-gauntlet-usdc-eth',
    protocol: 'morpho',
    chain: 'ethereum',
    token: 'USDC',
    apy: 0.071,
    apyMean30d: 0.068,
    apyBase: 0.071,
    apyReward: null,
    displayName: 'Morpho — Gauntlet USDC',
    outputTokenSymbol: 'gauntletUSDC',
    apyType: 'variable',
    tvlUsd: 120_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'morpho-steakhouse-usdc-eth',
    protocol: 'morpho',
    chain: 'ethereum',
    token: 'USDC',
    apy: 0.065,
    apyMean30d: 0.062,
    apyBase: 0.065,
    apyReward: null,
    displayName: 'Morpho — Steakhouse USDC',
    outputTokenSymbol: 'steakUSDC',
    apyType: 'variable',
    tvlUsd: 80_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'morpho-re7-weth-eth',
    protocol: 'morpho',
    chain: 'ethereum',
    token: 'WETH',
    apy: 0.034,
    apyMean30d: 0.031,
    apyBase: 0.034,
    apyReward: null,
    displayName: 'Morpho — Re7 WETH',
    outputTokenSymbol: 're7WETH',
    apyType: 'variable',
    tvlUsd: 40_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'euler-usdc-eth',
    protocol: 'euler',
    chain: 'ethereum',
    token: 'USDC',
    apy: 0.059,
    apyMean30d: 0.055,
    apyBase: 0.059,
    apyReward: null,
    displayName: 'Euler V2 — USDC',
    outputTokenSymbol: 'eUSDC',
    apyType: 'variable',
    tvlUsd: 30_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'euler-weth-eth',
    protocol: 'euler',
    chain: 'ethereum',
    token: 'WETH',
    apy: 0.028,
    apyMean30d: 0.025,
    apyBase: 0.028,
    apyReward: null,
    displayName: 'Euler V2 — WETH',
    outputTokenSymbol: 'eWETH',
    apyType: 'variable',
    tvlUsd: 25_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },

  // Arbitrum
  {
    id: 'aave-usdc-arb',
    protocol: 'aave',
    chain: 'arbitrum',
    token: 'USDC',
    apy: 0.044,
    apyMean30d: 0.042,
    apyBase: 0.044,
    apyReward: null,
    displayName: 'Aave V3 — USDC',
    outputTokenSymbol: 'aUSDC',
    apyType: 'variable',
    tvlUsd: 90_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'aave-weth-arb',
    protocol: 'aave',
    chain: 'arbitrum',
    token: 'WETH',
    apy: 0.019,
    apyMean30d: 0.018,
    apyBase: 0.019,
    apyReward: null,
    displayName: 'Aave V3 — WETH',
    outputTokenSymbol: 'aWETH',
    apyType: 'variable',
    tvlUsd: 110_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'morpho-gauntlet-usdc-arb',
    protocol: 'morpho',
    chain: 'arbitrum',
    token: 'USDC',
    apy: 0.068,
    apyMean30d: 0.065,
    apyBase: 0.068,
    apyReward: null,
    displayName: 'Morpho — Gauntlet USDC',
    outputTokenSymbol: 'gauntletUSDC',
    apyType: 'variable',
    tvlUsd: 45_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'euler-usdc-arb',
    protocol: 'euler',
    chain: 'arbitrum',
    token: 'USDC',
    apy: 0.057,
    apyMean30d: 0.053,
    apyBase: 0.057,
    apyReward: null,
    displayName: 'Euler V2 — USDC',
    outputTokenSymbol: 'eUSDC',
    apyType: 'variable',
    tvlUsd: 15_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },

  // Base
  {
    id: 'aave-usdc-base',
    protocol: 'aave',
    chain: 'base',
    token: 'USDC',
    apy: 0.041,
    apyMean30d: 0.039,
    apyBase: 0.041,
    apyReward: null,
    displayName: 'Aave V3 — USDC',
    outputTokenSymbol: 'aUSDC',
    apyType: 'variable',
    tvlUsd: 130_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'morpho-gauntlet-usdc-base',
    protocol: 'morpho',
    chain: 'base',
    token: 'USDC',
    apy: 0.068,
    apyMean30d: 0.065,
    apyBase: 0.068,
    apyReward: null,
    displayName: 'Morpho — Gauntlet USDC',
    outputTokenSymbol: 'gauntletUSDC',
    apyType: 'variable',
    tvlUsd: 65_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'morpho-usdc-base',
    protocol: 'morpho',
    chain: 'base',
    token: 'USDC',
    apy: 0.062,
    apyMean30d: 0.059,
    apyBase: 0.062,
    apyReward: null,
    displayName: 'Morpho — USDC Core',
    outputTokenSymbol: 'mUSDC',
    apyType: 'variable',
    tvlUsd: 25_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'euler-usdc-base',
    protocol: 'euler',
    chain: 'base',
    token: 'USDC',
    apy: 0.055,
    apyMean30d: 0.052,
    apyBase: 0.055,
    apyReward: null,
    displayName: 'Euler V2 — USDC',
    outputTokenSymbol: 'eUSDC',
    apyType: 'variable',
    tvlUsd: 12_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
  {
    id: 'euler-weth-base',
    protocol: 'euler',
    chain: 'base',
    token: 'WETH',
    apy: 0.024,
    apyMean30d: 0.022,
    apyBase: 0.024,
    apyReward: null,
    displayName: 'Euler V2 — WETH',
    outputTokenSymbol: 'eWETH',
    apyType: 'variable',
    tvlUsd: 10_000_000,
    rewardTokens: [],
    lockPeriodDays: null,
    lockDescription: null,
  },
]

export function getDepositDestinations(token: string, chain: ChainId): DepositDestination[] {
  return DEPOSIT_DESTINATIONS.filter(d => d.token === token && d.chain === chain)
    .sort((a, b) => b.apy - a.apy)  // highest APY first
}
